parsing requestId from message and stamping it as attribute
newrelic/aws-unified-lambda pull request #12
Opened 2024-12-18 07:25 UTC by hrai-nr

2024-12-18 09:15 UTC, sanathramesh commented on src/cloudwatch/cloudwatch.go
> +			if strings.HasPrefix(cloudwatchLogsData.LogGroup, common.LambdaLogGroup) {
nit : I don't think this if check needs to be a part of the for loop since every message is going to have the same log group

2024-12-18 09:26 UTC, sanathramesh reviewed
@hrai-nr 
 I don't think pr actually implements the feature similar to previous lambda implementation.
This is how the previous lambda worked :
Log Line 1 : START RequestId: d653fb2c-0234-46ff-ae6b-9a418b888420 Version: $LATEST INFO ERROR hrai
Log Line 2 : some random log 
If this was processed by previous lambda it would append the requestId to both the log lines.
The current implementation would not append the request Id to subsequent requests.

2024-12-18 09:43 UTC, sanathramesh reviewed
I  would suggest you to move the parsing logic to message_util. it would help in reusability and unit testing. 

Also please write unit tests

2025-01-04 09:13 UTC, nr-rkallempudi requested changes
Do not merge this PR until we agree on consistent approach to handle JSON payload as well. 

Refer Jira ticket: https://new-relic.atlassian.net/browse/NR-200593

2025-01-15 09:10 UTC, sanathramesh commented on src/util/message_util.go
> +	if requestID, ok := jsonMessage["requestId"].(string); ok {
Are you sure that the requestId can be at two different levels in the map.

2025-01-15 09:16 UTC, hrai-nr commented on src/util/message_util.go
> +	if requestID, ok := jsonMessage["requestId"].(string); ok {
Yes, see example below:
1. {
    "time": "2025-01-15T06:16:31.260Z",
    "type": "platform.start",
    "record": {
        "requestId": "5fa37a81-6f05-4cfc-a380-19c2b20ba8bb",
        "version": "$LATEST"
    }
}
Here it is in **record.requestId.**
2. 
{
    "timestamp": "2025-01-15T06:16:31Z",
    "level": "INFO",
    "message": "Validating BucketNames: hi himanshu",
    "logger": "root",
    "requestId": "5fa37a81-6f05-4cfc-a380-19c2b20ba8bb"
}
Here it is in **requestId**.

2025-01-16 06:10 UTC, sanathramesh submitted a review, later dismissed

2025-01-20 10:15 UTC, maya-jha requested changes

2025-01-20 10:15 UTC, maya-jha commented on src/cloudwatch/cloudwatch.go
> +				lastRequestID = util.AddRequestID(message, logAttribute, lastRequestID, regularExpression)
Can you update unit test for cloudwatch also? Add test there for multiple log messages.

2025-01-20 10:15 UTC, maya-jha commented on src/util/message_util.go
> +		if len(matches) == 2 {
When will this be 2? Can you add a comment for this?

2025-01-20 10:27 UTC, maya-jha commented
1. If lambda is running for longer time e.g. 5 minutes? Whats the behavior? Will this work in those cases?
2. If log stream is split across multiple payloads this will not work but that may be harder problem to fix.

2025-01-21 11:57 UTC, hrai-nr commented on src/cloudwatch/cloudwatch.go
> +				lastRequestID = util.AddRequestID(message, logAttribute, lastRequestID, regularExpression)
Added more testcases for full coverage

2025-01-21 11:57 UTC, hrai-nr commented on src/util/message_util.go
> +		if len(matches) == 2 {
Added

2025-01-21 11:57 UTC, hrai-nr commented on src/util/message_util.go
> +			logAttribute["requestId"] = lastRequestID
Added more test

2025-01-21 12:13 UTC, maya-jha commented
> 1. If lambda is running for longer time e.g. 5 minutes? Whats the behavior? Will this work in those cases?
> 2. If log stream is split across multiple payloads this will not work but that may be harder problem to fix.

test.

2025-01-21 12:54 UTC, nr-rkallempudi approved these changes

2025-01-21 12:55 UTC, merged