End to End tests - PART 1
newrelic/aws-unified-lambda pull request #13
Opened 2024-12-19 15:36 UTC by ahegdeNR

2025-01-02 11:45 UTC, voorepreethi submitted a review, later dismissed

2025-01-02 11:45 UTC, voorepreethi commented on .github/workflows/run-e2e-tests.yaml
> +          ./build-templates.sh
As it involves couple of script files, add a step or job to validate these script files. can use something like spellcheck

2025-01-02 11:45 UTC, voorepreethi commented on e2e-tests/lambda-s3-trigger.sh
> +delete_stack "$S3_TRIGGER_CASE"
Should we delete the resources only on success of stack , so that even if there is any issue in the deployment , the resources can be used to traceback

2025-01-02 11:45 UTC, voorepreethi commented on e2e-tests/build-templates.sh
> +  sam package --s3-bucket "$S3_BUCKET" --template-file "$BUILD_DIR/template.yaml" --output-template-file "$BUILD_DIR/$TEMPLATE_FILE"
As part of cleaning up of instances, delete the build file as well from the s3 bucket  which gets uploaded as part of this command

2025-01-03 06:35 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +      - name: Run e2e tests
This will run as part of merge workflow. Right now there are 2 separate workflows for lambda code deployment, templates push. This is a new workflow

2025-01-03 06:36 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +          ./build-templates.sh
If any of the scripts fail, the workflow step itself fails. All the required checks need to be added as part of the test files itself. There's no additional check required here

2025-01-03 06:37 UTC, ahegdeNR commented on e2e-tests/lambda-s3-trigger.sh
> +delete_stack "$S3_TRIGGER_CASE"
delete stack happens only of the stack is in create success state. Any other state the deletion fails and the step in workflow also fails.

2025-01-03 09:50 UTC, maya-jha requested changes

2025-01-03 09:50 UTC, maya-jha commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +validate_stack_resources() {
use more specific name may be `validate_lambda_subscription_created`

2025-01-06 09:27 UTC, ahegdeNR commented on e2e-tests/build-templates.sh
> +  sam package --s3-bucket "$S3_BUCKET" --template-file "$BUILD_DIR/template.yaml" --output-template-file "$BUILD_DIR/$TEMPLATE_FILE"
completed

2025-01-06 09:27 UTC, ahegdeNR commented on e2e-tests/common-scripts.sh
> +    --capabilities CAPABILITY_IAM
pushed this to trigger specific files

2025-01-06 09:34 UTC, ahegdeNR commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +  )
refactored

2025-01-06 09:35 UTC, ahegdeNR commented on e2e-tests/config-file.cfg
> +S3_BUCKET=unified-lambda-serverless-1
updated

2025-01-06 09:42 UTC, ahegdeNR commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +validate_stack_resources() {
modified

2025-01-07 07:42 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +          ./lambda-s3-trigger.sh
Hey @maya-jha running these tests in parallel is causing some sort of issue, cloudwatch stack parameters being picked by s3 stack. I'll take this up as a follow up in the upcoming prs for other cases.

2025-01-07 09:37 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +      - main
Right now I have added a rule that all checks need to pass before merge so that would stop code from getting merged to main if tests fail. We can try this out on develop branch for now.

2025-01-07 09:56 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +          ./lambda-s3-trigger.sh
completed

2025-01-08 05:40 UTC, maya-jha requested changes
thanks for addressing earlier comments.

2025-01-08 05:40 UTC, maya-jha commented on .github/workflows/run-e2e-tests.yaml
> +      - main
We also need to setup [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches) , [link 2](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)

2025-01-08 05:40 UTC, maya-jha commented on .github/workflows/run-e2e-tests.yaml
> +          # Run trigger s3 and cloudwatch trigger tests parallely
Can you add log statements here and elsewhere so that it would be easy to read test run details?

2025-01-08 09:16 UTC, hrai-nr commented on e2e-tests/common-scripts.sh
> +    sleep 60
We can change this to 30 Second, 60 second wait it too much, or we can implement exponential backoff. 
Exponential backoff is recommended and industry best practice.
Ref: https://www.pullrequest.com/blog/retrying-and-exponential-backoff-smart-strategies-for-robust-software/

2025-01-08 09:16 UTC, hrai-nr commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +deploy_cloudwatch_trigger_stack "$LAMBDA_TEMPLATE_BUILD_DIR/$LAMBDA_TEMPLATE" "$CLOUDWATCH_TRIGGER_CASE" "$NEW_RELIC_LICENSE_KEY" "$NEW_RELIC_REGION" "$NEW_RELIC_ACCOUNT_ID" "false"  "$LOG_GROUP_NAME
I'll recommend passing e2e-cloudwatch-trigger-stack as stack name which is a constant, can you add some random character so that it can be run multiple times in parallel.

2025-01-08 09:16 UTC, hrai-nr commented on e2e-tests/lambda-s3-trigger.sh
> +S3_TRIGGER_CASE=e2e-s3-trigger-stack
Same as above, we should append some character to make the stack name unique. (Let's say due to some reason delete failed for previous stack, then our test cases will start failing, or is someone created stack with same name manually. ) You can use something like this:

RANDOM_STRING=$(openssl rand -hex 4)
STACK_NAME="${DEFAULT_STACK_NAME}-${RANDOM_STRING}"

2025-01-08 09:16 UTC, hrai-nr commented on .github/workflows/run-e2e-tests.yaml
> +          ./lambda-cloudwatch-trigger.sh &
Instead of having two shell script and creating two different stacks, if we pass both S3 bucket name and log group to the sam deploy command, it will create a single stack with triggers on the S3 bucket and it will also create subscription filter on the log group passed, this way we can deploy everything in one stack and the same validation logic can validate everything.
This will help us save costs.

2025-01-08 09:16 UTC, hrai-nr commented on e2e-tests/lambda-s3-trigger.sh
> +  lambda_configurations=$(echo "$notification_configuration" |
Can you add some logs comment to help us better understand the code. Mention what cases in bucket and prefix you are validating.

2025-01-08 13:58 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +      - main
@maya-jha yes branch protection rules are in place, one at org level and one at repo level. Currently force push, delete, merging without approval, merging without all checks passing are prohibited. These are present for both develop and main branch

2025-01-08 14:04 UTC, ahegdeNR commented on e2e-tests/lambda-s3-trigger.sh
> +S3_TRIGGER_CASE=e2e-s3-trigger-stack
This is a good suggestion. But let's say the stack creation fails due to a bug. Then there would e2e tests failing for multiple merge requests and each would create multiple failing stacks. These will have to be then manually deleted. Let me know your thoughts.

2025-01-08 14:14 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +          # Run trigger s3 and cloudwatch trigger tests parallely
added

2025-01-08 14:24 UTC, ahegdeNR commented on e2e-tests/common-scripts.sh
> +    sleep 60
updated

2025-01-08 14:35 UTC, ahegdeNR commented on e2e-tests/lambda-s3-trigger.sh
> +  lambda_configurations=$(echo "$notification_configuration" |
updated

2025-01-09 08:56 UTC, hrai-nr approved these changes

2025-01-10 04:44 UTC, maya-jha requested changes
minor comments only.

2025-01-10 04:44 UTC, maya-jha commented on .github/workflows/run-e2e-tests.yaml
> +      - main
lets validate on develop branch. Do we need to update this  with actual checks after the first run?
![Screenshot 2025-01-10 at 9 57 26 AM](https://github.com/user-attachments/assets/8a96566e-0fce-421d-903d-27ced09e445e)

2025-01-10 04:44 UTC, maya-jha commented on .github/workflows/run-e2e-tests.yaml
> +          echo "cloudwatch trigger PID: $pid1"
nit: change to "Testing setting up cloudwatch trigger with PID: $pid1"

2025-01-10 04:44 UTC, maya-jha commented on .github/workflows/run-e2e-tests.yaml
> +          echo "s3 trigger PID: $pid2"
nit: change to "Testing setting up s3 trigger PID: $pid2"

2025-01-10 04:44 UTC, maya-jha commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +
nit: add echo statement here.

2025-01-10 04:44 UTC, maya-jha commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +validate_stack_deployment_status "$CLOUDWATCH_TRIGGER_CASE"
nit: add echo statement here and for each step.

2025-01-10 04:44 UTC, maya-jha commented on e2e-tests/lambda-s3-trigger.sh
> +deploy_s3_trigger_stack "$LAMBDA_TEMPLATE_BUILD_DIR/$LAMBDA_TEMPLATE" "$S3_TRIGGER_CASE" "$NEW_RELIC_LICENSE_KEY" "$NEW_RELIC_REGION" "$NEW_RELIC_ACCOUNT_ID" "false" "$S3_BUCKET_NAMES" "''"
nit: add echo statement here and for each step.

2025-01-10 05:39 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +      - main
Yes, I have added e2e tests for now, but I am not able to add any other checks. Not sure why

2025-01-10 05:39 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +          echo "cloudwatch trigger PID: $pid1"
completed

2025-01-10 05:39 UTC, ahegdeNR commented on .github/workflows/run-e2e-tests.yaml
> +          echo "s3 trigger PID: $pid2"
completed

2025-01-10 05:45 UTC, ahegdeNR commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +
completed

2025-01-10 05:45 UTC, ahegdeNR commented on e2e-tests/lambda-cloudwatch-trigger.sh
> +validate_stack_deployment_status "$CLOUDWATCH_TRIGGER_CASE"
completed

2025-01-10 05:45 UTC, ahegdeNR commented on e2e-tests/lambda-s3-trigger.sh
> +deploy_s3_trigger_stack "$LAMBDA_TEMPLATE_BUILD_DIR/$LAMBDA_TEMPLATE" "$S3_TRIGGER_CASE" "$NEW_RELIC_LICENSE_KEY" "$NEW_RELIC_REGION" "$NEW_RELIC_ACCOUNT_ID" "false" "$S3_BUCKET_NAMES" "''"
completed

2025-01-13 05:08 UTC, maya-jha approved these changes

2025-01-13 06:21 UTC, merged